[General]
__userfile__=true
iconTheme=

[desktopswitch]
alignment=Left
labelType=0
rows=2
showOnlyActive=false

[fancymenu]
buttonsAtTop=true
categoriesAtRight=false
favorites\1\desktopFile=/usr/share/applications/thunar.desktop
favorites\10\desktopFile=/usr/share/applications/xfce4-terminal.desktop
favorites\11\desktopFile=/usr/share/applications/virt-manager.desktop
favorites\2\desktopFile=/usr/share/applications/pcmanfm-qt.desktop
favorites\3\desktopFile=/usr/share/applications/org.x.editor.desktop
favorites\4\desktopFile=/usr/share/applications/chromium.desktop
favorites\5\desktopFile=/usr/share/applications/firefox.desktop
favorites\6\desktopFile=/usr/share/applications/org.wireshark.Wireshark.desktop
favorites\7\desktopFile=/usr/share/applications/onlyoffice-desktopeditors.desktop
favorites\8\desktopFile=/usr/share/applications/geany.desktop
favorites\9\desktopFile=/usr/share/applications/qterminal.desktop
favorites\size=11
icon=/usr/share/lxqt/graphics/lxqt-labwc.png
ownIcon=true
showText=true
text=software

[mount]
alignment=Right

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=28
lineCount=1
lockPanel=false
opacity=100
panelSize=42
plugins=fancymenu, desktopswitch, taskbar, statusnotifier, tray, mount, volume, worldclock, showdesktop
position=Bottom
reserve-space=true
screen-name=eDP-1
show-delay=0
visible-margin=true
width=100
width-percent=true

[taskbar]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=IconText
buttonWidth=220
closeOnMiddleClick=false
excludedList=
groupingEnabled=false
iconByClass=false
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=false
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=false
ungroupedNextToExisting=false
wheelDeltaThreshold=300
wheelEventsAction=1

[volume]
alignment=Right

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm:ss'</b><br/><font size=\"-2\">'ddd, d MMM yyyy'<br/>'TT'</font>'"
dateFormatType=custom
dateLongNames=false
datePadDay=true
datePosition=below
dateShowDoW=true
dateShowYear=false
defaultTimeZone=
formatType=custom-timeonly
showDate=true
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=true
timePadHour=true
timeShowSeconds=false
timeZoneWheel=true
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
useAdvancedManualFormat=false
